version: "3.8"

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: portfolio-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network

  # Optional: Development service
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "5173:5173"
    container_name: portfolio-dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - portfolio-network
    profiles:
      - dev

networks:
  portfolio-network:
    driver: bridge
